name: Jekyll site CI

on:
  push:
    branches: 
     - main
 

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        sudo rm -rf "/actions-runner/_work/css-html/css-html/.jekyll-cache"
        sudo chmod 666 /var/run/docker.sock
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future" -p 8080:80
